{% set version = "2.4.3" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: 51b81e1f1ee7f64a4ca1e9f61f01216c364a3f086a48b1be38eb057199cb19bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - networkx
    - numpy >=1.3
    - pandas >=1.0
    - scikit-learn
    - scipy >=1.0

test:
  imports:
    - mapclassify
    - mapclassify.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  dev_url: https://github.com/pysal/mapclassify

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
